name: "Infra: CVE checks"
on:
  pull_request:
    types: [ "opened", "reopened", "synchronize" ]
  push:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '0 8 15 * *'

permissions:
  contents: read

jobs:

  check-cves:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # infered from @v4
        with:
          token: ${{ github.token }}

      - name: Set up JDK
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # infered from @v4
        with:
          java-version-file: '.java-version'
          distribution: 'zulu'
          cache: 'gradle'

      - name: Build project
        id: build
        run: |
          ./gradlew clean build \
          -x test \
          -Pbuild-docker-images=true \
          -Pinclude-frontend=true \
          -Pversion=latest

      - name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # infered from @v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # infered from @v3

      - name: Cache Docker layers
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # infered from @v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build docker image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # infered from @v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: api
          platforms: linux/amd64
          push: false
          load: true
          tags: |
            ghcr.io/kafbat/kafka-ui:latest
          build-args: |
            JAR_FILE=build/libs/api-latest.jar
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Run CVE checks
        uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8 # infered from @v0.33.1
        with:
          image-ref: "ghcr.io/kafbat/kafka-ui:latest"
          format: "table"
          exit-code: "1"

  notify:
    needs: check-cves
    if: ${{ always() && needs.build-and-test.result == 'failure' && github.event_name == 'schedule' }}
    uses: ./.github/workflows/infra_discord_hook.yml
    with:
      message: "Attention! CVE checks run failed! Please fix them CVEs :("
    secrets:
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL_CVE }}
