name: "Frontend: build and test"

on:
  workflow_call:

permissions:
  contents: read

jobs:
  tests:
    env:
      CI: true
      NODE_ENV: dev
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # infered from @v4
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
          token: ${{ github.token }}

      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # infered from @v4.2.0
        with:
          version: 9.15.4

      - name: Install node
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # infered from @v3.9.1
        with:
          node-version: "22.12.0"
          cache: "pnpm"
          cache-dependency-path: "./frontend/pnpm-lock.yaml"

      - name: Install Node dependencies
        run: |
          cd frontend/
          pnpm install --frozen-lockfile

      - name: Compile
        run: |
          cd frontend/
          pnpm compile

      - name: Linter
        run: |
          cd frontend/
          pnpm lint:CI

      - name: Tests
        run: |
          cd frontend/
          pnpm test:CI

      # TODO check frontend sonar results in sonarcloud after migration to gradle
